name: radar
description: A new Flutter project.
publish_to: none
version: 1.0.43
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  smooth_page_indicator: ^1.1.0
  dio: ^5.4.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  http: ^1.1.0
  intl_phone_field: ^3.2.0
  flutter_otp_text_field: ^1.1.1
  intl: ^0.19.0
  qr_flutter: ^4.1.0
  webview_flutter: ^4.4.1
  email_validator: ^3.0.0
  badges: ^3.1.2
  permission_handler: ^11.3.1
  carousel_slider: ^4.2.1
  toggle_switch: ^2.3.0
  camera: ^0.11.0+1
  image_picker: ^1.0.4
  pie_chart: ^5.3.2
  textfield_tags: ^3.0.1
  another_flushbar: ^1.12.30
  percent_indicator: ^4.2.3
  dropdown_button2: ^2.3.9
  countries_flag: ^1.0.0
  lottie: ^3.1.2
  shared_preferences: ^2.2.2
  syncfusion_flutter_charts: ^26.1.39
  country_picker: ^2.0.21
  country_state_city_picker: ^1.2.8
  screenshot: ^3.0.0
  share_plus: ^9.0.0
  path_provider: ^2.1.1
  calendar_date_picker2: ^1.1.5
  gradient_borders: ^1.0.0
  simple_gradient_text: ^1.3.0
  persistent_bottom_nav_bar: any
  getwidget: ^4.0.0
  curved_navigation_bar: ^1.0.3
  sms_autofill: ^2.3.0
  flutter_svg: ^2.0.9
  simple_barcode_scanner: ^0.1.1
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  firebase_storage: ^12.0.1
  firebase_messaging: ^15.0.1
  geolocator: ^12.0.0
  flutter_image_compress: ^2.1.0
  cloud_firestore: ^5.0.1
  app_settings: ^5.1.1
  flutter_local_notifications: ^17.1.2
  google_maps_flutter: ^2.5.3
  no_screenshot: ^0.0.1+6
  url_launcher: ^6.2.4
  package_info_plus: ^8.0.0
  easy_localization: ^3.0.3
  country_code_picker: ^3.0.0
  libphonenumber_plugin: ^0.3.3
  socket_io_client: ^2.0.3+1
  web_socket_client: ^0.1.0
  web_socket_channel: ^3.0.0
  geocoding: ^3.0.0
  location: ^6.0.1
  internet_connection_checker_plus: ^2.2.0
  material_symbols_icons: ^4.2762.0
  device_info_plus: ^10.1.0
  pin_code_fields: ^8.0.1
  custom_rating_bar: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/icons/
  - assets/icons/profile_icon.png
  - assets/translations/
  fonts:
  - family: Poppins
    fonts:
    - asset: assets/fonts/Poppins-Light.ttf
      weight: 300
    - asset: assets/fonts/Poppins-Regular.ttf
      weight: 400
    - asset: assets/fonts/Poppins-Medium.ttf
      weight: 500
    - asset: assets/fonts/Poppins-SemiBold.ttf
      weight: 600
    - asset: assets/fonts/Poppins-Bold.ttf
